### ISSUE TITLE
Run Error: python flatten.py --help 

### ISSUE THREAD

**Issue by hanm2019** [HKUSTGZ-MICS-LYU/FlattenRTL#2]
When I run:
`python flatten.py --help`
get:
```
  File "flatten.py", line 14
    def visitModule_declaration(self, ctx: VerilogParser.Module_declarationContext):
                                         ^
SyntaxError: invalid syntax
```

**Comment by Jzjerry** [comment]
Hi,

Could you tell us more about your Python environment, like the Python version? 
I believe it's because of the type hint `ctx: VerilogParser.Module_declarationContext`, which should be supported starting from about Python 3.8 or higher.
So you might need to upgrade your Python.

**Comment by hanm2019** [comment]
Sorry, I run it in python2.7. When I switch to python 3.8, it works!
